version: '3.8'
services:
  rest-api:
    image: binotify-rest-service:latest
    ports:
      - 3000:3000
    hostname: api-binotify-rest-service
    env_file: .env
    volumes:
      - ./:/app
  postgresql:
    image: postgres:latest
    ports:
      - 5433:5432
    hostname: db-binotify-rest-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
networks:
  api-postgresql:
    driver: bridge